platform :ios, '8.0'
# Uncomment this line if you're using Swift

target 'XSBreakthrought' do
    pod 'MBProgressHUD'
    #手动布局
    pod 'Masonry'
    #pod 'XSBreakthrought', :git => 'https://github.com/xingshuaiEducation/XSBreakthrought.git'

end
